package cn.iocoder.yudao.module.jijian.service.query.ai;

import org.springframework.stereotype.Component;

/**
 * 提供 DeepSeek SQL Agent 可查询的业务表结构描述。
 * 不包含数据库账号、连接信息或系统表信息。
 */
@Component
public class JijianQuerySchemaProvider {

    private static final String SCHEMA_JSON = "{\n"
            + "  \"allowedTables\": [\n"
            + "    {\n"
            + "      \"tableName\": \"jijian_compensatory_leave\",\n"
            + "      \"description\": \"调休记录表\",\n"
            + "      \"columns\": [\n"
            + "        {\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},\n"
            + "        {\"name\":\"applicant_name\",\"type\":\"VARCHAR\",\"desc\":\"申请人姓名\"},\n"
            + "        {\"name\":\"employee_no\",\"type\":\"VARCHAR\",\"desc\":\"员工编号\"},\n"
            + "        {\"name\":\"department\",\"type\":\"VARCHAR\",\"desc\":\"部门名称\"},\n"
            + "        {\"name\":\"overtime_start_time\",\"type\":\"DATETIME\",\"desc\":\"加班开始时间\"},\n"
            + "        {\"name\":\"overtime_start_shift\",\"type\":\"VARCHAR\",\"desc\":\"加班开始班次（上午/下午）\"},\n"
            + "        {\"name\":\"overtime_end_time\",\"type\":\"DATETIME\",\"desc\":\"加班结束时间\"},\n"
            + "        {\"name\":\"overtime_end_shift\",\"type\":\"VARCHAR\",\"desc\":\"加班结束班次\"},\n"
            + "        {\"name\":\"compensatory_start_time\",\"type\":\"DATETIME\",\"desc\":\"调休开始时间\"},\n"
            + "        {\"name\":\"compensatory_start_shift\",\"type\":\"VARCHAR\",\"desc\":\"调休开始班次\"},\n"
            + "        {\"name\":\"compensatory_end_time\",\"type\":\"DATETIME\",\"desc\":\"调休结束时间\"},\n"
            + "        {\"name\":\"compensatory_end_shift\",\"type\":\"VARCHAR\",\"desc\":\"调休结束班次\"},\n"
            + "        {\"name\":\"compensatory_duration\",\"type\":\"DECIMAL\",\"desc\":\"调休时长（天）\"},\n"
            + "        {\"name\":\"is_outside\",\"type\":\"VARCHAR\",\"desc\":\"是否出义（原文：出义/不出义/是/否）\"},\n"
            + "        {\"name\":\"outside_location\",\"type\":\"VARCHAR\",\"desc\":\"出义地址\"},\n"
            + "        {\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},\n"
            + "        {\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记（0正常/1已删除，查询时必须加 deleted=0）\"}\n"
            + "      ],\n"
            + "      \"timeFields\": [\"compensatory_start_time\",\"overtime_start_time\"],\n"
            + "      \"personFields\": [\"applicant_name\",\"employee_no\"],\n"
            + "      \"deptField\": \"department\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\": \"jijian_leave_health\",\n"
            + "      \"description\": \"疗休养请假记录表\",\n"
            + "      \"columns\": [\n"
            + "        {\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},\n"
            + "        {\"name\":\"applicant_name\",\"type\":\"VARCHAR\",\"desc\":\"申请人姓名\"},\n"
            + "        {\"name\":\"employee_no\",\"type\":\"VARCHAR\",\"desc\":\"员工编号\"},\n"
            + "        {\"name\":\"department\",\"type\":\"VARCHAR\",\"desc\":\"部门名称\"},\n"
            + "        {\"name\":\"leave_location\",\"type\":\"VARCHAR\",\"desc\":\"疗休养地点\"},\n"
            + "        {\"name\":\"start_time\",\"type\":\"DATETIME\",\"desc\":\"开始时间\"},\n"
            + "        {\"name\":\"end_time\",\"type\":\"DATETIME\",\"desc\":\"结束时间\"},\n"
            + "        {\"name\":\"leave_days\",\"type\":\"DECIMAL\",\"desc\":\"请假天数\"},\n"
            + "        {\"name\":\"work_years\",\"type\":\"VARCHAR\",\"desc\":\"工龄\"},\n"
            + "        {\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},\n"
            + "        {\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记（查询时必须加 deleted=0）\"}\n"
            + "      ],\n"
            + "      \"timeFields\": [\"start_time\",\"end_time\"],\n"
            + "      \"personFields\": [\"applicant_name\",\"employee_no\"],\n"
            + "      \"deptField\": \"department\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\": \"jijian_leave_personal\",\n"
            + "      \"description\": \"事假记录表\",\n"
            + "      \"columns\": [\n"
            + "        {\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},\n"
            + "        {\"name\":\"applicant_name\",\"type\":\"VARCHAR\",\"desc\":\"申请人姓名\"},\n"
            + "        {\"name\":\"employee_no\",\"type\":\"VARCHAR\",\"desc\":\"员工编号\"},\n"
            + "        {\"name\":\"department\",\"type\":\"VARCHAR\",\"desc\":\"部门名称\"},\n"
            + "        {\"name\":\"leave_type\",\"type\":\"VARCHAR\",\"desc\":\"假别类型\"},\n"
            + "        {\"name\":\"leave_reason\",\"type\":\"VARCHAR\",\"desc\":\"请假事由\"},\n"
            + "        {\"name\":\"start_time\",\"type\":\"DATETIME\",\"desc\":\"开始时间\"},\n"
            + "        {\"name\":\"end_time\",\"type\":\"DATETIME\",\"desc\":\"结束时间\"},\n"
            + "        {\"name\":\"leave_days\",\"type\":\"DECIMAL\",\"desc\":\"请假天数\"},\n"
            + "        {\"name\":\"leave_status\",\"type\":\"VARCHAR\",\"desc\":\"状态\"},\n"
            + "        {\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},\n"
            + "        {\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记（查询时必须加 deleted=0）\"}\n"
            + "      ],\n"
            + "      \"timeFields\": [\"start_time\",\"end_time\"],\n"
            + "      \"personFields\": [\"applicant_name\",\"employee_no\"],\n"
            + "      \"deptField\": \"department\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\": \"jijian_business_trip\",\n"
            + "      \"description\": \"出差记录表\",\n"
            + "      \"columns\": [\n"
            + "        {\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},\n"
            + "        {\"name\":\"applicant_name\",\"type\":\"VARCHAR\",\"desc\":\"申请人姓名\"},\n"
            + "        {\"name\":\"employee_no\",\"type\":\"VARCHAR\",\"desc\":\"员工编号\"},\n"
            + "        {\"name\":\"department\",\"type\":\"VARCHAR\",\"desc\":\"部门名称\"},\n"
            + "        {\"name\":\"trip_reason\",\"type\":\"VARCHAR\",\"desc\":\"出差事由\"},\n"
            + "        {\"name\":\"departure_place\",\"type\":\"VARCHAR\",\"desc\":\"出发地\"},\n"
            + "        {\"name\":\"destination\",\"type\":\"VARCHAR\",\"desc\":\"目的地\"},\n"
            + "        {\"name\":\"start_date\",\"type\":\"DATETIME\",\"desc\":\"出差开始日期\"},\n"
            + "        {\"name\":\"end_date\",\"type\":\"DATETIME\",\"desc\":\"出差结束日期\"},\n"
            + "        {\"name\":\"trip_days\",\"type\":\"DECIMAL\",\"desc\":\"出差天数\"},\n"
            + "        {\"name\":\"trip_personnel\",\"type\":\"VARCHAR\",\"desc\":\"出差人员（逗号分隔）\"},\n"
            + "        {\"name\":\"trip_people_count\",\"type\":\"INT\",\"desc\":\"出差人数\"},\n"
            + "        {\"name\":\"is_outside\",\"type\":\"VARCHAR\",\"desc\":\"是否出义（原文：出义/不出义/是/否）\"},\n"
            + "        {\"name\":\"outside_location\",\"type\":\"VARCHAR\",\"desc\":\"出义地点\"},\n"
            + "        {\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},\n"
            + "        {\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记（查询时必须加 deleted=0）\"}\n"
            + "      ],\n"
            + "      \"timeFields\": [\"start_date\",\"end_date\"],\n"
            + "      \"personFields\": [\"applicant_name\",\"employee_no\"],\n"
            + "      \"deptField\": \"department\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\": \"jijian_attendance_daily\",\n"
            + "      \"description\": \"考勤日报表（每条记录为一人一天的打卡情况，数据量大，约每月1万+条）\",\n"
            + "      \"columns\": [\n"
            + "        {\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},\n"
            + "        {\"name\":\"employee_name\",\"type\":\"VARCHAR\",\"desc\":\"员工姓名（即姓名字段）\"},\n"
            + "        {\"name\":\"employee_no\",\"type\":\"VARCHAR\",\"desc\":\"员工编号，查询指定人员时优先用 employee_no\"},\n"
            + "        {\"name\":\"department\",\"type\":\"VARCHAR\",\"desc\":\"部门名称\"},\n"
            + "        {\"name\":\"attendance_date\",\"type\":\"DATE\",\"desc\":\"考勤日期（DATE类型，条件用 attendance_date='2026-04-03' 或 BETWEEN）\"},\n"
            + "        {\"name\":\"week_day\",\"type\":\"VARCHAR\",\"desc\":\"星期（如：星期一、星期五）\"},\n"
            + "        {\"name\":\"checkin_time\",\"type\":\"DATETIME\",\"desc\":\"上班打卡时间（包含日期和时间）\"},\n"
            + "        {\"name\":\"checkin_result\",\"type\":\"VARCHAR\",\"desc\":\"上班打卡结果，原样存储（正常/迟到/缺卡/异常等）\"},\n"
            + "        {\"name\":\"checkin_location\",\"type\":\"VARCHAR\",\"desc\":\"上班打卡地点\"},\n"
            + "        {\"name\":\"checkin_remark\",\"type\":\"VARCHAR\",\"desc\":\"上班备注\"},\n"
            + "        {\"name\":\"checkout_time\",\"type\":\"DATETIME\",\"desc\":\"下班打卡时间（包含日期和时间）\"},\n"
            + "        {\"name\":\"checkout_result\",\"type\":\"VARCHAR\",\"desc\":\"下班打卡结果，原样存储（正常/早退/缺卡/异常等）\"},\n"
            + "        {\"name\":\"checkout_location\",\"type\":\"VARCHAR\",\"desc\":\"下班打卡地点\"},\n"
            + "        {\"name\":\"checkout_remark\",\"type\":\"VARCHAR\",\"desc\":\"下班备注\"},\n"
            + "        {\"name\":\"source_parsed_data_id\",\"type\":\"BIGINT\",\"desc\":\"来源导入批次ID\"},\n"
            + "        {\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记（0正常/1已删除，查询时必须加 deleted=0）\"}\n"
            + "      ],\n"
            + "      \"timeFields\": [\"attendance_date\",\"checkin_time\",\"checkout_time\"],\n"
            + "      \"personFields\": [\"employee_name\",\"employee_no\"],\n"
            + "      \"deptField\": \"department\",\n"
            + "      \"importantNote\": \"【字段规范】①人员姓名用 employee_name（不是 applicant_name）；②员工编号用 employee_no；③上班打卡地点用 checkin_location；④下班打卡地点用 checkout_location；⑤判断迟到/缺卡/早退查 checkin_result 或 checkout_result（值为原文字符串：正常/迟到/缺卡/早退/未打卡 等）；⑥考勤日期用 attendance_date（DATE类型），星期用 week_day；⑦所有查询必须加 deleted=0；⑧该表每月约1万+条，分析时必须使用 COUNT/GROUP BY/SUM 聚合统计，禁止 SELECT * 全表扫描。\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\":\"jijian_property\",\"description\":\"房产情况表\",\n"
            + "      \"columns\":["
            + "{\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},"
            + "{\"name\":\"property_address\",\"type\":\"VARCHAR\",\"desc\":\"房产地址\"},"
            + "{\"name\":\"property_name\",\"type\":\"VARCHAR\",\"desc\":\"房产名称\"},"
            + "{\"name\":\"ownership_info\",\"type\":\"VARCHAR\",\"desc\":\"产权信息\"},"
            + "{\"name\":\"building_time\",\"type\":\"DATETIME\",\"desc\":\"建筑时间\"},"
            + "{\"name\":\"area\",\"type\":\"DECIMAL\",\"desc\":\"建筑面积\"},"
            + "{\"name\":\"lease_status\",\"type\":\"VARCHAR\",\"desc\":\"租赁情况\"},"
            + "{\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},"
            + "{\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记\"}],\n"
            + "      \"joinKeys\":{\"jijian_lease_contract\":\"jijian_property.id = jijian_lease_contract.property_id\"}\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\":\"jijian_lessee\",\"description\":\"租赁人员表（敏感证件和联系方式不开放）\",\n"
            + "      \"columns\":["
            + "{\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},"
            + "{\"name\":\"entity_type\",\"type\":\"VARCHAR\",\"desc\":\"主体类型\"},"
            + "{\"name\":\"contact_name\",\"type\":\"VARCHAR\",\"desc\":\"联系人姓名\"},"
            + "{\"name\":\"is_internal_staff\",\"type\":\"TINYINT\",\"desc\":\"是否单位内部人员\"},"
            + "{\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},"
            + "{\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记\"}],\n"
            + "      \"joinKeys\":{\"jijian_lease_contract\":\"jijian_lessee.id = jijian_lease_contract.lessee_id\"}\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\":\"jijian_lease_contract\",\"description\":\"租赁合同表\",\n"
            + "      \"columns\":["
            + "{\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},"
            + "{\"name\":\"property_id\",\"type\":\"BIGINT\",\"desc\":\"关联房产ID\"},"
            + "{\"name\":\"lessee_id\",\"type\":\"BIGINT\",\"desc\":\"关联租赁人员ID\"},"
            + "{\"name\":\"contract_start_time\",\"type\":\"DATETIME\",\"desc\":\"合同开始时间\"},"
            + "{\"name\":\"contract_end_time\",\"type\":\"DATETIME\",\"desc\":\"合同结束时间\"},"
            + "{\"name\":\"amount\",\"type\":\"DECIMAL\",\"desc\":\"合同金额\"},"
            + "{\"name\":\"payment_status\",\"type\":\"VARCHAR\",\"desc\":\"支付情况\"},"
            + "{\"name\":\"water_electricity_mgmt\",\"type\":\"VARCHAR\",\"desc\":\"水电费管理方式\"},"
            + "{\"name\":\"contract_summary\",\"type\":\"TEXT\",\"desc\":\"合同摘要\"},"
            + "{\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},"
            + "{\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记\"}]\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\":\"jijian_canteen_supplier\",\"description\":\"食堂供应价格表\",\n"
            + "      \"columns\":["
            + "{\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},"
            + "{\"name\":\"item_name\",\"type\":\"VARCHAR\",\"desc\":\"项目名称\"},"
            + "{\"name\":\"spec_level\",\"type\":\"VARCHAR\",\"desc\":\"规格等级\"},"
            + "{\"name\":\"unit\",\"type\":\"VARCHAR\",\"desc\":\"单位\"},"
            + "{\"name\":\"quantity\",\"type\":\"DECIMAL\",\"desc\":\"数量\"},"
            + "{\"name\":\"price\",\"type\":\"DECIMAL\",\"desc\":\"单价\"},"
            + "{\"name\":\"subtotal\",\"type\":\"DECIMAL\",\"desc\":\"小计\"},"
            + "{\"name\":\"supplier_name\",\"type\":\"VARCHAR\",\"desc\":\"供应商名称\"},"
            + "{\"name\":\"supply_date\",\"type\":\"DATE\",\"desc\":\"供应日期\"},"
            + "{\"name\":\"purchase_point\",\"type\":\"VARCHAR\",\"desc\":\"采价点\"},"
            + "{\"name\":\"remark\",\"type\":\"VARCHAR\",\"desc\":\"备注\"},"
            + "{\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记\"}]\n"
            + "    },\n"
            + "    {\n"
            + "      \"tableName\":\"jijian_canteen_market_price\",\"description\":\"义乌市民生商品市场零售价格信息公告表\",\n"
            + "      \"columns\":["
            + "{\"name\":\"id\",\"type\":\"BIGINT\",\"desc\":\"主键ID\"},"
            + "{\"name\":\"item_name\",\"type\":\"VARCHAR\",\"desc\":\"项目名称/商品名称\"},"
            + "{\"name\":\"spec_level\",\"type\":\"VARCHAR\",\"desc\":\"规格/等级\"},"
            + "{\"name\":\"unit\",\"type\":\"VARCHAR\",\"desc\":\"单位\"},"
            + "{\"name\":\"price\",\"type\":\"DECIMAL\",\"desc\":\"价格\"},"
            + "{\"name\":\"price_point\",\"type\":\"VARCHAR\",\"desc\":\"采价点\"},"
            + "{\"name\":\"price_month\",\"type\":\"VARCHAR\",\"desc\":\"公告年月，格式如 2025-02\"},"
            + "{\"name\":\"source_title\",\"type\":\"VARCHAR\",\"desc\":\"公告标题\"},"
            + "{\"name\":\"source_file_name\",\"type\":\"VARCHAR\",\"desc\":\"来源文件名\"},"
            + "{\"name\":\"source_parsed_data_id\",\"type\":\"BIGINT\",\"desc\":\"来源导入批次ID\"},"
            + "{\"name\":\"deleted\",\"type\":\"TINYINT\",\"desc\":\"逻辑删除标记\"}],\n"
            + "      \"compareRule\":\"按 item_name 相同、price_month 相同聚合同一商品同月不同采价点价格，可计算最高价、最低价、均价、差额。\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"rules\": [\n"
            + "    \"所有查询必须加 deleted = 0 条件\",\n"
            + "    \"jijian_attendance_daily 数据量大，必须用聚合查询\",\n"
            + "    \"时间范围用 >= 和 < 区间条件\",\n"
            + "    \"房产、租赁人员、租赁合同仅允许按 schema 声明的主外键关联\",\n"
            + "    \"不允许访问 system_/infra_/oauth/mysql/information_schema 等系统表\",\n"
            + "    \"不允许 SELECT 手机号/身份证/营业执照等敏感字段原文\"\n"
            + "  ]\n"
            + "}";

    public String schemaJson() {
        return SCHEMA_JSON;
    }

    public boolean isAllowedTable(String tableName) {
        if (tableName == null) return false;
        String lower = tableName.toLowerCase().trim();
        return lower.equals("jijian_compensatory_leave")
                || lower.equals("jijian_leave_health")
                || lower.equals("jijian_leave_personal")
                || lower.equals("jijian_business_trip")
                || lower.equals("jijian_attendance_daily")
                || lower.equals("jijian_property")
                || lower.equals("jijian_lessee")
                || lower.equals("jijian_lease_contract")
                || lower.equals("jijian_canteen_supplier")
                || lower.equals("jijian_canteen_market_price");
    }
}
