CREATE TABLE IF NOT EXISTS `jijian_operation_audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `user_id` bigint DEFAULT NULL COMMENT '操作用户编号',
  `user_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作用户名称快照',
  `operation_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '操作类型，如 query/import/delete/disposal',
  `module_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'jijian' COMMENT '模块名称',
  `target_table` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标业务表',
  `target_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目标记录ID或批次ID',
  `request_summary` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '请求摘要',
  `result_summary` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '结果摘要',
  `success` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否成功',
  `error_message` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败信息',
  `client_ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户端 IP',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_jijian_operation_audit_user_time` (`user_id`, `create_time`),
  KEY `idx_jijian_operation_audit_type_time` (`operation_type`, `create_time`),
  KEY `idx_jijian_operation_audit_target` (`target_table`, `target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='纪检操作审计日志';
