CREATE TABLE IF NOT EXISTS `jijian_query_history` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键编号',
  `user_id` bigint NOT NULL COMMENT '查询用户编号',
  `user_name` varchar(64) DEFAULT NULL COMMENT '查询用户名称快照',
  `question` text NOT NULL COMMENT '用户原始问题',
  `answer` longtext DEFAULT NULL COMMENT 'AI 回答',
  `query_type` varchar(32) NOT NULL COMMENT '查询类型：chat/agent_chat',
  `form_type` varchar(64) DEFAULT NULL COMMENT '识别到的表类型',
  `query_sql` longtext DEFAULT NULL COMMENT '经过安全校验的只读 SQL',
  `query_result_json` longtext DEFAULT NULL COMMENT '脱敏后的查询结果 JSON 快照',
  `database_context_meta_json` longtext DEFAULT NULL COMMENT '数据库上下文元信息 JSON',
  `model_name` varchar(128) DEFAULT NULL COMMENT '模型或 AI 模式',
  `success` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否成功',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '失败信息',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_user_create_time` (`user_id`, `create_time`),
  KEY `idx_query_type` (`query_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='纪检智能查询历史';
